### ISSUE TITLE
Migrate to github actions

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-tool_pdfpages#33]

**Comment by Damola12345** [comment]
hi @dmitriim can i help you out with the migration to gh_action ?

**Comment by dmitriim** [comment]
Oh. Didn't realise there is already one https://github.com/catalyst/moodle-tool_pdfpages/issues/28 

@Damola12345 sure. Feel free to submit PR.

See docs on what would we expect here https://github.com/catalyst/catalyst-moodle-workflows/tree/v2-with-release-and-docs and an example is here https://github.com/catalyst/moodle-tool_cloudmetrics

**Comment by Damola12345** [comment]
okay @dmitriim will submit soon

**Comment by dmitriim** [comment]
Sorry @Damola12345  I have just done that.
